### ISSUE TITLE
Creation of annotation in OpenLayers is broken

### ISSUE THREAD

**Issue by ewg118** [annotorious/annotorious-v1#102]
The latest Github JS is broken when creating an annotation. You can test it out on the annotorious demo page. It was working sometime last week.

**Comment by rsimon** [comment]
Ouch - sure sign the OpenLayers integration badly needs some unit tests ;-) Thanks for letting me know, Ethan - fixed now!

**Comment by cheekygit** [comment]
I don't get it. The demo page uses two years old version 1.2.5 of annotator. Does Annotorious not work with the current 1.2.9?

**Comment by rsimon** [comment]
OpenLayers support is generally not available on the Annotator plugin. See issue #103 for further info.
