### ISSUE TITLE
addAnnotation(new,old) does not replace old in 0.6.3

### ISSUE THREAD

**Issue by jrvosse** [annotorious/annotorious-v1#104]
When I add a new annotation and give the old one to replace as the second parameter, the old one is not removed, leaving two annotations.

If the old annotation has the same shape as the new one, this even leads to hash collisions (causing annotorious to crash when clicking on the edit button).

To reproduce, just add/replace the annotation made in test/image/index.html :

 var annotation = {
          src: '640px-Hallstatt.jpg',
          text: 'This is an annotation.',
          editable: true,
          shapes: [{
            type: 'rect',
            units: 'pixel',
            geometry: {x: 100, y: 80, width: 60, height: 50}
          }]
        };
        var annotation2 = {
          src: '640px-Hallstatt.jpg',
          text: 'This is annotation 2.',
          editable: true,
          shapes: [{
            type: 'rect',
            units: 'pixel',
            geometry: {x: 100, y: 80, width: 60, height: 50}
          }]
        };

```
    anno.addAnnotation(annotation);
    anno.addAnnotation(annotation2, annotation);
```

**Comment by rsimon** [comment]
Thanks for spotting this! I added a fix & it's live on the hosted version at http://annotorious.github.io/latest/annotorious.min.js

Cheers,
R

**Comment by jrvosse** [comment]
Thanks for the quick fix!

I confirm the latest version in git now works for me. So I close this issue.

Jacco
