### ISSUE TITLE
Non english comment encoding

### ISSUE THREAD

**Issue by BLorant** [annotorious/annotorious-v1#126]
Is there a way to change the encoding in the comments? I need to use non english characters and all it gives me is jiberish.

**Comment by rsimon** [comment]
Hi. Hm, could this be a page encoding issue? I just tried with, e.g. Greek characters and German umlauts on the [demo page](http://annotorious.github.io) and things were displayed fine. 

Does adding

```
<meta charset="UTF-8">
```

to the page help in your case?

**Comment by BLorant** [comment]
HI!

Yes it is an encoding issue. Sorry for the post I figured its with the whole page but 
<meta charset="UTF-8">
is added to the page and the problem still exists.

**Comment by rsimon** [comment]
Hi,

can you provide a more detailed report of your problem? As I said: I tried creating an annotation with Greek script on the demo page. After storing the annotation, the popup displays the text just fine. If you can describe the steps you are making, and the results you are getting, I may be able to reproduce your problem.

Cheers,
R

**Comment by BLorant** [comment]
Well I'm using Spring Mvc  and the problem is when i get the text from the element on the Front-end its fine but when I pass the parameters to the server with an ajax call on the server side its full of "?". It does not matter if its a pathVariable or a modelAttribute. But my problem is clearly not with Annotarious.

**Comment by gsergiu** [comment]
So .. I assume you have a similar problem to the one described in the following post .. isn’t it?
http://stackoverflow.com/questions/11350918/spring-mvc-request-encode-issue

Br,
Sergiu

**Comment by BLorant** [comment]
Thanks for the help! I Solved it it was a spring config issue.

**Comment by gsergiu** [comment]
Hi Lorant,

It would be nice if you share the changes you made in the spring/server configurations with as. They might be usefull as a reference for other people that are building backends for Annotatorious.

Thank you in advance!
Sergiu
