### ISSUE TITLE
Issue while trying to get the co-ordinates of annotation

### ISSUE THREAD

**Issue by sulthanallaudeen** [annotorious/annotorious-v1#134]
I just wanted to store the all co-ordinates of annotation made in my browser. so i was trying to access the console log which gives the co-ordinates.

While i export the log, i am getting something like this

sc {type: "mousedown", target: canvas.annotorious-item.annotorious-opacity-fade.annotorious-item-focus, currentTarget: canvas.annotorious-item.annotorious-opacity-fade.annotorious-item-focus, relatedTarget: null, offsetX: 220…}
sc {type: "mousemove", target: canvas.annotorious-item.annotorious-opacity-fade, currentTarget: canvas.annotorious-item.annotorious-opacity-fade, relatedTarget: null, offsetX: 220…}
sc {type: "mousemove", target: canvas.annotorious-item.annotorious-opacity-fade, currentTarget: canvas.annotorious-item.annotorious-opacity-fade, relatedTarget: null, offsetX: 221…}

How can i get the co-ordinates.

My aim is to save the annotation in back end and make the annotation appear on next time.. (Is there any way recommended to achieve it)

**Comment by rsimon** [comment]
Are you looking for a way to retrieve an annotation after it has been created by the user? See:

http://annotorious.github.io/api.html#addHandler

The _onAnnotationCreated_ event is the one you're probably looking for.

**Comment by sulthanallaudeen** [comment]
Thanks for the link.. 

Yes, I want to retrieve an annotation after it has been creation by the user.. 

console.log(annotation.text);

Is this enough for me to capture all the annotations that is marked in the image ?

**Comment by rsimon** [comment]
The event handler will return a (single) annotation at the time it is created. If you want to get all annotations currently on the page, independently of any user events, this is what you're looking for:

http://annotorious.github.io/api.html#getAnnotations

**Comment by sulthanallaudeen** [comment]
Thanks, i got the solution. :+1:
