### ISSUE TITLE
PDF Demo missing

### ISSUE THREAD

**Issue by sulthanallaudeen** [annotorious/annotorious-v1#135]
I can see that "allowing the annotation of PDFs, EPUBs, videos, images, sound, and more." in the link http://annotatorjs.org/

But i can't able to see any demo which uses PDF to annotate. 

Is there any demo which uses PDF to annotate ?

**Comment by rsimon** [comment]
Annotorious is a different project than Annotator.js. It's true that (an older version of) Annotorious existed as a plugin to (an older version of) Annotator.js. But apart from that, they are totally different things.

Anntorious works only on images.

**Comment by sulthanallaudeen** [comment]
Is there any plugin or extension by Annotorious which allows me to annotate on PDF ?

**Comment by rsimon** [comment]
I don't know. Did you get in touch with the developers of Annotator.js?

**Comment by sulthanallaudeen** [comment]
No, I didn't so far.. 

I should ask about the PDF issue here 

https://github.com/openannotation/annotator/

Isn't it  ?

**Comment by rsimon** [comment]
Yes, I think that's the official repo.

**Comment by sulthanallaudeen** [comment]
Thanks. So, annotorious supports only image and the annotation made can be recovered later.. Is't it ?

**Comment by rsimon** [comment]
Yes, see http://annotorious.github.io/ for examples, and http://annotorious.github.io/api.html for a full overview of the JavaScript API.

**Comment by sulthanallaudeen** [comment]
Thanks, I will make note of it
