### ISSUE TITLE
Annotations stored automatically

### ISSUE THREAD

**Issue by sulthanallaudeen** [annotorious/annotorious-v1#136]
I wonder today morning, that i can see few annotation are being stored and it is retrieved even after closing and opening the image.. How it is possible..

Is this a feature or bug.. Can anyone pls tell me

**Comment by sulthanallaudeen** [comment]
I noted that the request are sent to 

https://api.parse.com/1/classes/Annotation

with the details such as 

---

_ApplicationId,
_ClientVersion
_InstallationId,
_JavaScriptKey
context,
shapes
src
text

---

If all those request sent are reached properly, then why are most of the annotation not retrieved... (Only few are saved and retrieved)

**Comment by rsimon** [comment]
1. Are you aware that you're using the Parse.com storage Plugin? This is the reason your annotations are being stored.
2. Did you copy the code from the demo page at an notorious.github.io? I suspect you are storing against the Parse account of the demo page. If so, please set up your own account with Parse.com. (The demo account has probably reached the free quota limit, which is why annotations are being discarded.)

**Comment by sulthanallaudeen** [comment]
Thanks,
Just now i noted that the request is going from

http://www.parsecdn.com/js/parse-1.2.8.min.js

In the line

serverURL="https://api.parse.com","undefined"!=typeof process&&process.versions&&process.versions.node&&(e._isNode=!0),e.initialize=function

I just copied the file to local right now.

I am not trying to beautify the file and need to do my own call there.. 

Is that good way to do like this ?

**Comment by sulthanallaudeen** [comment]
or may i know where  i can have my own call and may i know the parameter names of the co-ordinates and notes typed.  

Or May i know where i can get the "shapes"  value in the js file ?

**Comment by rsimon** [comment]
As I said above: the file you are looking is the Parse.com API implementation, and you have obviously been using the Parse.com storage plugin without knowing. 

Do you realize your page includes something like the code below somewhere?

```
    <script type="text/javascript" src="http://annotorious.github.io/latest/anno-parse-plugin.js"></script>
    <script>
      anno.addPlugin('Parse', { app_id: '...', js_key: '...' });
    </script>
```

Remove this if you don't want to use the Parse plugin. 

Yes, you can use your own code to store and retrieve annotations, as discussed in Issue #134 yesterday. Please take a moment to read the Annotorious API documentation:

http://annotorious.github.io/api.html

You may also want to take some time to download the Annotorious release ZIP and take a look at the 'Hello World' example included there.

**Comment by sulthanallaudeen** [comment]
Thanks for suggestion. Yes i should start from first. 

i will remove the parse plugin, 

I have downloaded the Annotorious release zip,

and i was looking at the /annotorious-0.6.3/example/example.html

but i can't find  a better call there

Can you suggest me an example to start with it.

Thanks
