### ISSUE TITLE
Annotation update not firing

### ISSUE THREAD

**Issue by sulthanallaudeen** [annotorious/annotorious-v1#138]
I am trying to call an alert whenever the annotation is updated.

I am using this 

onAnnotationUpdated(annotation)
    {
            alert('updated');
    }

also tried

anno.onAnnotationUpdated(annotation)
    {
            alert('updated');
    }

The script is at the top of the page after all .js file are called.

What is the mistake i am doing  ?

**Comment by rsimon** [comment]
Please take time to read the documentation at http://annotorious.github.io/api.html#addHandler. The proper code is 

```
anno.addHandler('onAnnotationUpdated', function(annotation) {
    alert('updated');
});
```

**Comment by sulthanallaudeen** [comment]
Thanks a lot.. Sure i do take time to read the documentation. Actually i am following that only...

But i still cannot find why i am not able to see the annotation at initial stage

Here is my code 

I have declared the variable myAnnotation and the param values inside..

```
var myAnnotations = {
  src : 'http://192.168.1.58/annotate/drive/image/Koala.jpg',
  text : 'My annotation',
style : [{

   }],
  shapes : [{
    type : 'rect',
    units: 'pixel',
    geometry : { x : 0.1825726141078838, y: 0.23756906077348067, width : 0.11602209944751381, height: 0.11618257261410789 }
}]
```

}

what should i  do next to make the annotation appear. 

Thanks

**Comment by rsimon** [comment]
Annotorious does not store annotations! It's a purely client-side library. If you want to store an annotation, you need to implement your own mechanism. This means:
1. Catching annotations when they are created - and using your own code to store them somewhere as objects: in local store, by posting them to a backend as JSON, etc.
2. When a page loads, you need your own code to retrieve the annotations stored earlier, and re-add them to the image using anno.addAnnotation.

Quoting from the API docs:

---

```
anno.addAnnotation(annotation, opt_replace)
```

Adds a new annotation, or replaces an existing one. In the latter case, the parameter opt_replace is the annotation to replace.

Annotations are object literals, according to the following example:

```
var myAnnotation = {
    /** The URL of the image where the annotation should go **/
    src : 'http://www.example.com/myimage.jpg',

    /** The annotation text **/
    text : 'My annotation',

    /** The annotation shape **/
    shapes : [{
        /** The shape type **/
        type : 'rect',

        /** The shape geometry (relative coordinates) **/
        geometry : { x : 0.1, y: 0.1, width : 0.4, height: 0.3 }
    }]
}
```

**Comment by rsimon** [comment]
So the line of code to make myAnnotation (re)appear would be

```
anno.addAnnotation(myAnnotation);
```

**Comment by sulthanallaudeen** [comment]
Thanks,

Yes even i tried the same way  .. i.e., 

declared 

var myAnnotations = {
    src : 'http://192.168.1.58/annotate/drive/image/Koala.jpg',
    text : 'My annotation',
    shapes : [{
        type : 'rect',
        geometry : { x : 0.1825726141078838, y: 0.23756906077348067, width : 0.11602209944751381, height: 0.11618257261410789 }
    }]
}

and then 

  anno.addAnnotation(myAnnotations);

in the document ready .. But annotation is not appearing on the image.. I am sure that the image name is right..

What might be the problem .. ? 

Thanks

**Comment by rsimon** [comment]
Check if the image URLs are identical. If you create an annotation on your image, does it have _exactly_ the same URL as you are putting into myAnnotations.src?

**Comment by sulthanallaudeen** [comment]
I have checked it several times. they are same... still i am facing the error

**Comment by rsimon** [comment]
Can you please post your entire code, or do you have a demo page online which reproduces the issue?

**Comment by sulthanallaudeen** [comment]
Shall i share my teamviewer id so that you can also check it.. It was in my local machine... 

Here is my gist : 

https://gist.github.com/sulthanallaudeen/2d8bc11cc7740b0fcec6

**Comment by sulthanallaudeen** [comment]
Why i ask because this project makes me really interesting. That's the reason i really wanted to do all the operations.. I have done with other handlers like save, update, delete etc., 

Due to the stuck up in the automatic annotate i am little worried.

If you need i shall share my teamviewer credentials so that you can see the probem directly.. 

Thanks

**Comment by rsimon** [comment]
You're using anno.addAnnotatoin outside of the init function. That means that at the time you are adding the annotation, annotorious is not initialized yet. Move anno.addAnnotation into init(), and things work. 

At least that's the change that made it work for me. I replaced your image with a random one for my own test (using a Koala, to stick with the spirit).

**Comment by sulthanallaudeen** [comment]
wow !! Thank's great.. it works as expected...
