### ISSUE TITLE
Making multiple annotation in document ready

### ISSUE THREAD

**Issue by sulthanallaudeen** [annotorious/annotorious-v1#139]
I was trying to have multiple annotation in the document ready.

I should do this for single annotation 

var myAnnotations = {
    src : 'http://192.168.1.58/annotate/drive/image/Koala.jpg',
    text : 'Suresh and Gopinath',
    shapes : [{
        type : 'rect',
        geometry : { x : 0.1825726141078838, y: 0.23756906077348067, width : 0.11602209944751381, height: 0.11618257261410789 }
    }]
}

and then 

anno.addAnnotation(myAnnotations);

How can i make multiple annotation in the document ready..

**Comment by sulthanallaudeen** [comment]
Here i saw one response from parser.. 

{"results":[{"context":"http://localhost:60576/RAPIDZoom/TestAno.html","createdAt":"2015-08-21T00:07:03.089Z","objectId":"Us4dccVf0H","shapes":[{"geometry":{"height":0.2071500015258789,"width":0.1562499761581421,"x":0.31042187213897704,"y":0.3930999755859375},"type":"rect"}],"src":"http://localhost:60576/RAPIDZoom/DZI/640px-Hallstatt.jpg","text":"test 2","updatedAt":"2015-08-21T17:16:17.269Z"},{"context":"http://annotorious.github.io/demos/semantic-tagging-preview.html","createdAt":"2015-08-24T10:38:40.085Z","objectId":"IXvsuaObHW","shapes":[{"geometry":{"height":0.0925,"width":0.1078125,"x":0.790625,"y":0.86},"style":{},"type":"rect"}],"src":"http://semantic-tagging-image.example.com","text":"Vienna here.","updatedAt":"2015-08-24T10:39:03.432Z"}]}

I referred here.. but i can't get any idea to make multiple annotation appear in document ready..

[If i see how the variable should be then i will give the response from service file.. So, that i can make my own api calls to achieve it]

Thanks

**Comment by rsimon** [comment]
I think I still don't quite understand what you are trying to achieve. You know how to add one annotation, right? So if you want to add multiple annotations, just repeat the same step. I.e. take an array of annotation objects, and iterate over it, calling anno.addAnnotation in each loop iteration.

What do you mean by "parser"? Do you refer to the JSON payloads of the Parse.com storage plugin? If so, what you see there is simply the annotation data going across the wire between the browser and the Parse.com storage backend. If you are planning to use your own backend, you need to take care of the HTTP/AJAX transfer anyway - but that's a separate issue.

**Comment by sulthanallaudeen** [comment]
Hey thanks,
i thought there would be some function if i have my annotation as array.

Thanks, i have followed what you have said..

Returned all the annotation as array from db, then iterated through each element :100: 

Thanks
