### ISSUE TITLE
0.6.4 Release

### ISSUE THREAD

**Issue by steviemo** [annotorious/annotorious-v1#142]
Hey folks,
Is there any chance of cutting a 0.6.4 release? New event handling has been introduced for clicking annotations which isn't available in 0.6.3 - would love to make use of this feature - I can't figure a way to register a custom event via a plugin.

Thanks,
Stephen

**Comment by rsimon** [comment]
Good point! I rolled a new release package: https://github.com/annotorious/annotorious/releases/tag/v0.6.4

Cheers,
Rainer

**Comment by steviemo** [comment]
closing as release made
