### ISSUE TITLE
Annotorious annotation covers up Openseadragon's default toolbar buttons

### ISSUE THREAD

**Issue by meihuisu** [annotorious/annotorious-v1#153]
When Openseadragon's toolbar buttons falls under an Annotorious annotation,
 their functions get masked. When using just Openseadragon's default overlay function, the buttons maintain their functions even when they are covered by an overlay. This is because of the z-index assigned to annotation in Annotorious in src/mediatypes/openseadragon/openseadragon.viewer.js around line #163.  Suggestion to maintain buttons function under a annotation?

**Comment by meihuisu** [comment]
Decided not to touch the Z-index and moved the control outside of the viewport.

**Comment by apricea4** [comment]
Hello @meihuisu could you give me some insight into how to get these two libraries working together?  I have the same problem as you in that my image covers up the OSD controls (I'll solve it same way you did I guess), but more importantly I cannot get the activateSelector to work or makeAnnotable for that matter.  I have anno.makeAnnotatable(viewer) just under the viewer definition, then outside of that div tag I have a button that calls anno.activateSelector() but on that button click I can still pan the image around.  Is this similar to what you did?  Did you run into the same issues as me?
Thanks

**Comment by meihuisu** [comment]
@apricea4, grep for annoSetup or makeAnnotatable from js/osd.annotorious.js from
https://github.com/informatics-isi-edu/openseadragon-viewer.git.  This is the base code 
for several different flavors of a viewer based on OSD.
