### ISSUE TITLE
Set Annotation text programmatically?

### ISSUE THREAD

**Issue by aenany-atmosphereiot** [annotorious/annotorious-v1#188]
Is it possible to update an annotation programmatically through some API method like setAnnotation(object) ? I don't intend for users to manually enter an annotation ... thanks !

**Comment by klarycantone** [comment]
hello please tell me how I can take the annotation to include it in the database thanks

**Comment by kalu-ghodakiya** [comment]
Hi
You can use anno.addAnnotation(); for add annotation in image.

**Comment by FlyingBugs** [comment]
is there any id associated with annotation object?

**Comment by gtopsis** [comment]
Maybe the only way to identify an annotation is by its geometry field. I havent found an id so far
