### ISSUE TITLE
how to use this  in angular 4 

### ISSUE THREAD

**Issue by rvuyyuru1** [annotorious/annotorious-v1#202]
i want to use this in component.ts file 
error while running
 Cannot find name 'anno'

**Comment by nagarajuchappa** [comment]
it may helps to you
https://github.com/igorlino/angular-annotorious

**Comment by rvuyyuru1** [comment]
I want this completely in angular 4 like i want to use anno object in component.ts file

**Comment by diazenal** [comment]
const anno = window['anno'];

**Comment by rvuyyuru1** [comment]
Thank you so much it works
