### ISSUE TITLE
Question/favor related to the documentation on the API

### ISSUE THREAD

**Issue by Thaimon** [annotorious/annotorious-v1#27]
Hi,

Firstoff I would like to say that I really like and apreciate the work you guys do. 

My programming skills aren't that advanced, so I was wondering if you could update the documentation on the Annotation Javascript API.

I'm working on a custom implementation of the script, but so far I've only succeded in creating an annotation after clicking on a button, however removing it with a remove button or returning the annotation information still remains a mistery to me.

I would really apreciate it, if you could give some more explanation about these functions or maybe a demo in which these functions are demonstrated

**Comment by rsimon** [comment]
Hi!

You are catching us in the middle of a bit of a transition phase - so not everything works just yet. 'removeAnnotation' was one such thing ;-) I added a quick patch now to make anno.removeAnnotation work. (It's already live in the hosted version at http://annotorious.github.com/latest/annotorious.min.js, and will be fully operational in the 0.2 release.)

I'll post an update to the Wiki shortly - so watch this space. In the mean time, you can also take a look at the test page here, which includes sample .addAnnotation/.removeAnnotation code: 

https://github.com/annotorious/annotorious/blob/master/test/plugins/plugin-hello-world.html

Cheers,
Rainer

**Comment by Thaimon** [comment]
Hey Rainer,

Thanks for your fast response!

Awsome, I'm gonna give it a spin :p

**Comment by Thaimon** [comment]
Hey Rainer,

I've incorporated some example controls in the example page.
You can view it at http://www.thaimon.com/annotorious/example.html

I dont know how to get the get annotation button working.
I was trying to display the annotation data beneith the buttons or in an alert, but I didn't succeed.

Maybe you can complete the example controls or point me in the right direction.

**Comment by rsimon** [comment]
Hi,

since you are adding the annotation yourself ("var church") you can simply keep a handle on it & there's no need for a 'get' via the anno object.

**However:** the API is going to change a little in the near future. the addAnnotation method will return some sort of (numeric) key you can keep as a handle instead; and there will be _listAnnotations_, _getAnnotation(key)_ and _highlightAnnotation(key)_ methods as well. I guess this is what you're looking for? Not sure how fast I can get this done, but I'm working on it :-)

Cheers,
Rainer

**Comment by Thaimon** [comment]
Oke thanks.

But how would I get the annotation data from annotations made by clicking and dragging?
And for instance display the data in an alert?

**Comment by rsimon** [comment]
Also with the listAnnotations method (as soon as it exists) or by listening for annotation create events. It will work like this:

```
anno.addHandler('onAnnotationCreated', function(annotation) {
  // Do something with the annotation, e.g. log text to console
  console.log(annotation.text);
});
```

The functionality is already wired 'inside' the _anno_ JavaScript class (see [here](https://github.com/annotorious/annotorious/blob/master/src/annotorious.js)), but it's not yet exposed to the outside yet.

**Comment by Thaimon** [comment]
Oke Rainer,

Keep up the good work!

**Comment by rsimon** [comment]
Hi, just a quick update: both `anno.addHandler` and `anno.getAnnotations` are now available as 'Alpha'! Restrictions: 
- there will be problems in lazy loading case - i.e. if you try to add/get annotations to/from images that are not yet
  visible on the screen
- the `getAnnotations` method **always** requires the URL of the image as a parameter.

I'll fix both issues in the near future & will also update the Wiki accordingly. In the mean time, you can again take a look at the (updated) test page at

https://github.com/annotorious/annotorious/blob/master/test/plugins/plugin-hello-world.html

**Comment by Thaimon** [comment]
That's Great news!

I'm so glad right now haha.

**Comment by rsimon** [comment]
Restrictions described above are fixed & documentation on the Wiki is updated!

https://github.com/annotorious/annotorious/wiki/JavaScript-API

I'm closing the issue!
