### ISSUE TITLE
OKFN Plugin: Initialization failure (primarily Chrome?)

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious-v1#3]
Sometimes the OKFN plugin fails to initialize properly. This can be seen easily, when the layout of the test page is completely messed up. Seems to happen more often in Chrome, but I could also observe it in Firefox occasionally.

My suspicion is that this is due to a race condition when both the OKFN Annotator and Yuma are manipulating the page's DOM at the same time. Could it help to move the instantiation code (now directly in YumaImagePlugin.prototype.pluginInit) into an onload handler?

**Comment by jamiefolsom** [comment]
Hi Rainer, haven't seen this bug, but I am not seeing the Annotator button on the image at all. Works on text on your demo page, but click-drag to create a box on the image doesn't do anything (rather, the browser appears to want to let me drag-drop the image itself, as it would with an non-annotatable image). Chrome/OS X? http://rsimon.github.com/yuma2/index_okfn.html Great to see your progress on this!

**Comment by rsimon** [comment]
Hi Jamie, interesting that layout isn't affected in your case. But it still looks like the exact same issue, as the rest of what you're describing is identical. I'll see that I can try out my fix attempt ASAP. Thx, Rainer

**Comment by jamiefolsom** [comment]
Gotcha. Let me know if I can help, testing, etc. Thanks.

**Comment by rsimon** [comment]
Ok, my attempt to fix this is in. Would be great if you could re-check and let me know. I'll also do some more testing tomorrow myself.

**Comment by jamiefolsom** [comment]
Hi Rainer, 

Works great for me in Chrome on OS X; nice work, and very exciting! 

Jamie

**Comment by rsimon** [comment]
Excellent - I'll do more testing on my end, then will clean up the (now rather messy) patch a bit & then we can hopefully close this issue. Thanks a lot for your help testing this!

Cheers,
R
