### ISSUE TITLE
Support relative coordinates

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious-v1#32]
In addition to unit:'pixel' also support unit:'fraction' (compare Digilib format). unit:'fraction' should be default. This is rather urgent to get the Wordpress plugin working correctly.

**Comment by mushon** [comment]
Is there indeed a WP plugin for Annotorious?

**Comment by rsimon** [comment]
Hi! I know there is one under development by @diggy, called "WP-Annotorious". But I don't know the current status, I'm afraid :-(

**Comment by diggy** [comment]
@rsimon @mushon A beta of the WP plugin is as good as ready, it'll soon be available for testing! Repo: https://github.com/diggy/wp-annotorious

**Comment by MarkoArsenovic** [comment]
does anyone know is it possible to annotate with pixel unit, not just relative and how?

**Comment by dosstx** [comment]
Very interested in using this for Wordpress. Anyone know if one was ever released?
