### ISSUE TITLE
Support for replies

### ISSUE THREAD

**Issue by synth** [annotorious/annotorious-v1#34]
Does annotorius/annotator support replies to an annotation?

Yuma previously did: http://yuma-js.github.com/demos/image-with-replies

I couldn't find a reference to it anywhere in the documentation or source code.

**Comment by rsimon** [comment]
Neither Annotorious nor Annotator (I assume you are referring to the OKFN Annotator, to which Annotorious can be used as a Plugin) do. However, AFAIK there is a plugin to OKFN Annotator, and I'm also planning to do a similar reply-thread plugin for Annotorious, which would then look pretty identical to the previous Yuma reply-threading mode. Can't give any firm dates or roadmap for this yet, unforunately though.

**Comment by synth** [comment]
Hypothes.is seems to be doing it(https://github.com/hypothesis/h, https://test.hypothes.is/), I've reached out to them to see if they can help.  I can see that they've forked okfn's annotator...

**Comment by rsimon** [comment]
Moved to 'Plugin Ideas' Wiki page.
