### ISSUE TITLE
deps.js not found (404) with generated okfn_plugin 

### ISSUE THREAD

**Issue by xavirec** [annotorious/annotorious-v1#35]
I try solved this by defining in okfn_plugin.json:

"define": {
   ..
   "goog.global.CLOSURE_NO_DEPS": true
   }

but doesn't worked.

P.S: Thank you for all

**Comment by rsimon** [comment]
Hi! I'm not sure what the problem is you are referring to. Can you provide more details? The Annotorious script generally doesn't load any dependencies at runtime. Or is this something you observed during development? When?

**Comment by rsimon** [comment]
Another thought: this might have been caused by the fact that the build file was switched to 'RAW' not 'ADVANCED' mode. Changed now. Can you check again?

**Comment by xavirec** [comment]
You are right. It is solved. When I was building the file with mode "RAW" in okfn_plugin.json 

java -jar plovr/plovr.jar build okfn_plugin.json > annotorious.js

Then it was necessary to include the javascript in this way:

```
<script type="text/javascript">
    CLOSURE_NO_DEPS = true;
</script>
<script src='annotorious.js'></script>
```

But, if I build the file with mode "ADVANCED" in okfn_plugin.json, need only include annotorious.js

Thanks for your help!

**Comment by rsimon** [comment]
Excellent. You're welcome!

Cheers,
R
