### ISSUE TITLE
Google Drive as backend

### ISSUE THREAD

**Issue by basmaat** [annotorious/annotorious-v1#38]
Recently the google drive sdk added annotations. It would be nice to be able to use this as the backend, for storing annotations. https://developers.google.com/drive/v2/reference/comments/get

**Comment by rsimon** [comment]
Excellent suggestion! This could be perfectly implemented as a Plugin. See the example [Elastic Search plugin](https://github.com/annotorious/annotorious/blob/master/src/plugins/elasticsearch.js) and/or the [Wiki docs](https://github.com/annotorious/annotorious/wiki/Developing-Plugins).

I'll try to take a closer look into the Google Drive API spec. Realistically, though, I won't have the time to do this myself anytime soon. I'm very happy to support anyone who's willing to give it a try, however! Any takers?

**Comment by rsimon** [comment]
Moved to 'Plugin Ideas' Wiki page.
