### ISSUE TITLE
First use of Annotorious 

### ISSUE THREAD

**Issue by itaizi** [annotorious/annotorious-v1#59]
Hi,

I tried to use your Annotorious tool.
I downloaded it from http://annotorious.github.com, but I got only the min.js.
So I went to https://github.com/annotorious/annotorious/tree/master/src, but I get a run-time exception 'goog' is undefined.

I just want the basic annotorious but not minified. It has all the functionality I need.
Where can I find it? How can I make it work?

I need to make a few changes to the base code.

Thanks.

**Comment by rsimon** [comment]
Hi Inbal,

I'm using the [Google Closure tools](https://developers.google.com/closure/) to build Annotorious. Therefore, the un-minified code depends on the Closure base library. (This is the reason for the exception you are seeing.)

If you need to make changes to the code, the best way is to fork Annotorious to your own repository and then follow the [developer instructions on the Wiki](https://github.com/annotorious/annotorious/wiki/Developers). Don't forget to send a pull request once you've fixed or added stuff! 

Cheers,
Rainer

**Comment by itaizi** [comment]
Hi Rainer, 

Thank you for your quick reply!
I followed developer instructions on the Wiki, but when I tried to open test/image/image_standalone.html I got an error 'anno' is undefined.

I am using asp.net, and I tried to create my own .aspx file. I added:
    <link rel="stylesheet" href="../../css/theme-dark/annotorious-dark.css" type="text/css" />
    <script src="http://localhost:myport/compile?id=annotorious"></script>

and an image tag with class="annotatable"

I can see the image, but nothing happens when I try to click and drag on the image.
(in this case I get no error)
What am I doing wrong?
Thanks again..

**Comment by rsimon** [comment]
Hi Inbal,

that means that plovr is not properly running to serve the compiled Annotorious script. Can you forward me the output from the plovr console window? 

Cheers,
Rainer

**Comment by itaizi** [comment]
You are right! I tried to run it again, and now it works!
Thank you very much.

But how can I debug the .js? my breakpoints are not hit

**Comment by rsimon** [comment]
Perfect! I'm closing the issue then.
Cheers,
Rainer

**Comment by itaizi** [comment]
Hi, I justv asked how can I debug the .js? my breakpoints are not hit

**Comment by rsimon** [comment]
I don't normally work with breakpoints, so I can't really give any advice here I'm afraid. Please refer to the [documentation of the Closure compiler](https://developers.google.com/closure/compiler/) and [the plovr build tool](http://plovr.com/options.html#debug).

PS: The plovr build properties are configured in [standalone.json](https://github.com/annotorious/annotorious/blob/master/standalone.json) and [okfn_plugin.json](https://github.com/annotorious/annotorious/blob/master/okfn_plugin.json) for the Annotorious standalone and Annotator-Plugin versions, respectively.

**Comment by PravinkumarA** [comment]
Hi,
How can i make this js work for dynamic image creation, like using jquery img.load(function(){});
