### ISSUE TITLE
"Write to Dropbox" plug-out

### ISSUE THREAD

**Issue by behas** [annotorious/annotorious-v1#63]
(This is to keep track of an idea for a possible extension.)

Problem: users want to use annotorious but don't have the infrastructure or technical skills to run a back-end.

Possible Solution: a "dropbox" plug-out stores all created annotations in a (shared) dropbox folder. This probably requires that the user first grants access for an annotorious dropbox plugin. This blog-post describes a possible solution: https://tech.dropbox.com/2012/08/some-love-for-javascript-applications-2/

**Comment by rsimon** [comment]
Great idea! I'm moving this to the corresponding ["Plugin Ideas" Wiki page](https://github.com/annotorious/annotorious/wiki/Plugin-Ideas)!
