### ISSUE TITLE
Can't make multiple images annotatable with 'class' 

### ISSUE THREAD

**Issue by noahwhite** [annotorious/annotorious-v1#72]
I have a simple prototype which displays 2 jpg images in a DIV. I annotated both <img> tags with class="annotatable" however only the 1st image becomes annotatable.

The only way I was able to get both images to become annotatable was to use the programatic approach.

I'm using the latest annotorious dist from github.io.

**Comment by rsimon** [comment]
Hi!

Hm - I can't reproduce this problem. I tried with three images on a test page, 1st and 3rd marked up with `class="annotatable"`, 2nd made annotatable programmatically on page load, and all three were fine.

Do you have some HTML source code you can post? Are images loaded and/or moved into view via JavaScript? If so, it could interfere with the lazy loading. (Images made annotatable via the CSS class are only made annotatable when moved into view, based on a page scroll listener. I.e. if they are out of view, and then moved into view without the page scrolling, it will be a problem.)

Cheers,
Rainer

**Comment by noahwhite** [comment]
```
<!DOCTYPE html>
<html>
<head>
    <title>Image Tagger</title>
    <link type="text/css" rel="stylesheet" href="vendor/annotorious-0.6/css/annotorious.css"/>
    <script type="text/javascript" src="vendor/annotorious-0.6/annotorious.min.js"></script>
</head>
<body>
    <header>
        <h1>Images</h1>
    </header>
    <img src="images/1_million.jpg" class="annotatable"/>
    <img src="images/catch_the_pass.jpg" class="annotatable"/>
</body>
</html>
```

**Comment by noahwhite** [comment]
Accidentally hit the close button. OK, so that's the simple HTML file that demonstrates the issue in my environment. I downloaded the 0.6 distribution locally and reference the js and css. In this instance only 1_million.jpg is annotatable in the browser.
