### ISSUE TITLE
Paths in okfn_plugin.json are wrong

### ISSUE THREAD

**Issue by noahwhite** [annotorious/annotorious-v1#73]
Many of the paths in this file do not match the actual directory structure and as a result executing the okfn plovr server and accessing the test page result in file not found errors in from the server.

**Comment by noahwhite** [comment]
After modifying the paths in okfn_plugin.jso to agree with the available file, including changing humanEventTypes.js to events.ui.js, and running plovr in VERBOSE mode, I am seeing the following errors:

``` javascript
E:\sandbox\github\annotorious\externs\api.externs.js:75: ERROR - Variable Annotator first declared in E:\sandbox\github\annotorious\externs\okfn_annotator.externs.js
var Annotator = { 
^
src/mediatypes/image/image.viewer.js:249: ERROR - variable console is undeclared
console.log('WARNING unsupported shape type: ' + shape.type); 
^
src/okfn/okfn_popup.js:1: ERROR - Variable humanEvents first declared in src/okfn/okfn_image_plugin.js
var humanEvents = annotorious.humanEvents; 
^
src/okfn/okfn_popup.js:157: ERROR - variable xy is undeclared
goog.style.setPosition(this._okfnAnnotator.viewer.element[0], xy.x, xy.y); 
^
src/shape/shape.js:197: ERROR - variable JSON is undeclared
return JSON.stringify(shape.geometry); 
^
```

**Comment by rsimon** [comment]
Ouch - yes, I made some made restructuring on the whole code base, and the OKFN integration was a little left behind... should be fixed now!

Cheers,
Rainer

**Comment by noahwhite** [comment]
Thanks that looks good now. The only other related nit is the wiki https://github.com/annotorious/annotorious/wiki/Developers#hacking-on-annotorious  references `test/image/index_okfn.html` but its currently `test/okfn/image_okfn.html`

**Comment by rsimon** [comment]
Good point. Fixed! Thx :-)
