### ISSUE TITLE
Touch Issue on hideSelectionWIdget

### ISSUE THREAD

**Issue by meeravk** [annotorious/annotorious-v1#77]
There seems to be an issue on hiding the SelectionWidget. Already loaded annotations are not showing on touch/tap after hiding the selection widget.

**Comment by rsimon** [comment]
Well observed! :-) Sorry, a bug - I pushed a fix. It should be synced to [http://annotorious.github.io/latest/annotorious.min.js](http://annotorious.github.io/latest/annotorious.min.js) within a couple of minutes!

**Comment by meeravk** [comment]
Thanks..Issue got fixed :)
