### ISSUE TITLE
Redefining '$' variable

### ISSUE THREAD

**Issue by eknight7** [annotorious/annotorious-v1#80]
Why does the script use '$' variable? I can't use jquery with this script unless I type 'jQuery'. But more importantly, if I am using annotorious and I want to use the lazy load plugin at http://www.appelsiini.net/projects/lazyload, then what can I do so that the scripts don't get confused with the '$' variable?

**Comment by rsimon** [comment]
I'm afraid that's a property of the Closure compiler, and beyond my control. Keep in mind that recommended practice is to use jQuery in "no conflict mode" in this case:

http://learn.jquery.com/using-jquery-core/avoid-conflicts-other-libraries/

**Comment by eknight7** [comment]
Oh ok. If its possible, can you provide a link to an example or give a short example of using annotorious with an external lazy load image library? Thanks.

**Comment by rsimon** [comment]
Added instructions to the 'Getting Started' page.
