### ISSUE TITLE
addAnnotation doesn't work on example page

### ISSUE THREAD

**Issue by zub0r** [annotorious/annotorious-v1#83]
Running this code in js console on example page does nothing.

```
a  = {
  /** The URL of the image where the annotation should go **/
  src : 'http://www.example.com/myimage.jpg',

  /** The annotation text **/
  text : 'My annotation',

  /** The annotation shape **/
  shapes : [{
    /** The shape type **/
    type : 'rect',

    /** The shape geometry (relative coordinates) **/
    geometry : { x : 0.1, y: 0.1, width : 0.4, height: 0.3 }
  }]
} 

anno.addAnnotation(a);  

```

Am I doing something wrong, or is it a bug? Thanks

**Comment by rsimon** [comment]
Hi Martin,

are you referring to 'example.html' from the 0.6 release package? Are you pasting _exactly_ the code below? This code will try to add an annotation to an image wit SRC "http://www.example.com/myimage.jpg" - which is not in that page. Instead, you'll need to add the annotation to an image which is actually on the page. The URL of the demo image is likely something like file:///home/rainer/my-download-location/example/640px-Hallstatt.jpg on your system, depending on which operating system you have, and where you unzipped the download package.

Note: the 0.6 release only supports absolute URLs, sorry. The next release will support relative URLs, so you will simply be able to use "src: '640px-Hallstatt.jpg'. If you want, you can replace the annotorious.min.js file from the release package with the latest dev version from http://annotorious.github.io/latest/annotorious.min.js. That version already supports .addAnnotation with relative URLs.)

Hope this helps,
Rainer

---

Von: Martin Haviar [notifications@github.com]
Gesendet: Montag, 21. Oktober 2013 20:00
An: annotorious/annotorious
Betreff: [annotorious] addAnnotation doesn't work on example page (#83)

Running this code in js console on example page does nothing.

a  = {
  /*\* The URL of the image where the annotation should go **/
  src : 'http://www.example.com/myimage.jpg',

  /*\* The annotation text **/
  text : 'My annotation',

  /*\* The annotation shape **/
  shapes : [{
    /** The shape type **/
    type : 'rect',

```
/** The shape geometry (relative coordinates) **/
geometry : { x : 0.1, y: 0.1, width : 0.4, height: 0.3 }
```

  }]
}

anno.addAnnotation(a);

Am I doing something wrong, or is it a bug? Thanks

**Comment by zub0r** [comment]
Thanks for quick response. Example page works fine when I set propper image.
What I am struggling with now is loading annotations from json after storing them in database with anno.getAnnotations(). Is there any extra step I need to do?

Calling

```
  $(window).load(function() {    
      var annotations = [{"src":"http://localhost:3000/upload/task_files/original/12.jpg?1382189378","text":"asdfasdf\n","shapes":[{"type":"rect","geometry":{"x":0.10966981132075472,"width":0.5035377358490566,"y":0.16352201257861634,"height":0.48270440251572333}}],"context":"http://localhost:3000/task_files/12"}];
      anno.addAnnotation(annotations[0]);        
  });
```

causes type error

```
r.z = function(a, b) {
    var c;
    c = a.src;
    if (!(0 < c.indexOf("://"))) {
        var d = document.createElement("a");
        d.href = c;
        c = d.protocol + "//" + d.host + d.pathname
    }
    a.src = c;
    (c = $(this, a.src)) && c.z(a, b)     // << Uncaught TypeError: Object [object Object] has no method 'z'
};
```

Thanks

**Comment by rsimon** [comment]
Hm - looks as if you're adding the annotation before the page has been loaded. Can you try moving your code into a &lt;script&gt; tag at the end of the body?

Cheers,
R

**Comment by zub0r** [comment]
I've tried all methods - using document ready, window load, even delay, nothing helped.
Maybe a conflict with other script.. Can I download unminimized script somewhere to debug it? 
Thanks

**Comment by rsimon** [comment]
Weird... yes conflict could be possible. You can get a "less minified version" (Google Closure has a peculiar way of handling minification) from http://annotorious.github.io/latest/annotorious.dev.js

cheers,
R

---

Von: Martin Haviar [notifications@github.com]
Gesendet: Dienstag, 22. Oktober 2013 19:43
An: annotorious/annotorious
Cc: Simon Rainer
Betreff: Re: [annotorious] addAnnotation doesn't work on example page (#83)

I've tried all methods - using document ready, window load, even delay, nothing helped.
Maybe a conflict with other script.. Can I download unminimized script somewhere to debug it?
Thanks

**Comment by rsimon** [comment]
Just realized you have a query param on your image URL. Maybe there s a bug left, and that s causing it. Can t look into it right now (on the road...) but will try to reproduce ASAP.

Cheers,
R

**Comment by zub0r** [comment]
Negative, I've tried param on example page and it worked.
Sadly, problematic part is minified id dev script.
Sory for bothering you with this..

2013/10/22 Rainer Simon notifications@github.com

**Comment by rsimon** [comment]
Could you forward me the complete test page for this? (I think you can add attachments to GitHub comments if I'm not mistaken...)

**Comment by zub0r** [comment]
I just solved it. Problem was conflict with jQuery $ variable.
I included annotorious after all other js files and used this code everywhere

```
jQuery( document ).ready(function( $ ) {
   // jQuery code here
}
```

.. and it worked!
You mentioned this in https://github.com/annotorious/annotorious/issues/80 - that jQuery should be used in no-colflict mode. Maybe it would be a good idea to add it to getting started page, it might save time for somebody else.

Thanks for help!

**Comment by rsimon** [comment]
Hi Martin,

excellent - thanks for taking the time to track this down. Yes - I'll definitely add this to the "getting started" guide on the Web page, plus at some prominent location on the Wiki.

Cheers,
Rainer

---

Von: Martin Haviar [notifications@github.com]
Gesendet: Mittwoch, 23. Oktober 2013 11:12
An: annotorious/annotorious
Cc: Simon Rainer
Betreff: Re: [annotorious] addAnnotation doesn't work on example page (#83)

I just solved it. Problem was conflict with jQuery $ variable.
I included annotorious after all other js files and used this code everywhere

jQuery( document ).ready(function( $ ) {
   // jQuery code here
}

.. and it worked!
You mentioned this in #80https://github.com/annotorious/annotorious/issues/80 - that jQuery should be used in no-colflict mode. Maybe it would be a good idea to add it to getting started page, it might save time for somebody else.

Thanks for help!

**Comment by abhaysaraf** [comment]
I have wrapped the entire code inside setTimeout it worked.
I have loaded 2 JS in the following order in my HTML:

```
<script src="../annotorious.min.js"></script>
<script src="../my.js"></script>
```

And **my.js** has below code:

```
setTimeout(function(){
// Add annotation code here
}, 2000);
```

but I am wondering why on ready not working. I do not want to sleep for 2 seconds. 

```
jQuery( document ).ready(function( $ ) {
   // jQuery code here
}
```

**Comment by martinconroy** [comment]
I can confirm, that for me, only adding a delay as above worked

**Comment by gajendra7590** [comment]
Thanks @abhaysaraf abhaysaraf Your answer worked but may i know why here delay is necesory
