### ISSUE TITLE
click and drag over image appears on top left corner but no actual rectangle appears

### ISSUE THREAD

**Issue by doesntwork** [annotorious/annotorious-v1#93]
I got the annotorious to load and the top left corner displays the message instruction with the leaf icon.

however when I actually click and drag on the image, nothing happens . I check the console, no error appears.

I check the networks tab and annotorious has loaded.

any help? it's notoriously hard to get annotorious working.

**Comment by rsimon** [comment]
Sounds like a timing issue. You are most likely making an image annotatable before it is fully loaded.

Are you using CSS selector-based activation? Are you using .makeAnnotatable() inside a load event handler? Where in your HTML source code are you adding the Annotorious script (head/body)? Are you loading images dynamically via JavaScript (e.g. via a lazy load lib)? Ideally, do you have a sample page online?

This thread might be related: https://groups.google.com/forum/#!topic/annotorious/XM-KANrckU0

**Comment by doesntwork** [comment]
guys I am absolutely losing it

this is so motherfucking trivial yet I can't get it to work extremely frustrating excuse the french but i'm just frustrated right now

now I am getting

Uncaught TypeError: Cannot read property 'length' of undefined 

I am no longer getting the leaf icon anymore.

I am using css class with annotatable on the img tag

```
    <script src="js/jquery-2.0.3.min.js" type="text/javascript"></script>
    <script src="annotorious/annotorious.min.js" type="text/javascript"></script>   
```

is declared right before the body tag

what's frustrating is that it's very hard to debug so I can't even begin to solve it.

unfortunately there's no really good alternative to annotorious, but if someone does have one please tell me as I have had it with this shit.

**Comment by rsimon** [comment]
_&lt;as I have had it with this shit&gt;_

No worries - it's always great to do things for free in your spare time & get this kind of feedback. Don't bother answering my questions above either. The answers might have been helpful in resolving the issue, that's all.

**Comment by mat-mathews** [comment]
@rsimon I personally really appreciate the quality of code in Annotorious. Thx very much for the hard work!

**Comment by rsimon** [comment]
Thanks! :-)

**Comment by pieroit** [comment]
Run into the same issue, try the jQuery.load() method:

```
// find widgets and make them annotable
$('img').each(function(i, el){

    // wait for image to be fully loaded
    $(this).load( function(){

        // start annotorius on the image
        anno.makeAnnotatable(this);
    });
});
```

**Comment by ramesh8** [comment]
Thanks @rsimon and @pieroit, i got the issue solved. used load function like suggested
`$('#aimage').load(function(){  
  anno.makeAnnotatable(document.getElementById('aimage'));
});`

annotorious, thanks again.

**Comment by gitanupam** [comment]
@pieroit's solution worked for me in 2020 as well. 

I reduced the image size to 35% and saw that I could annotate outside the image but not over the image (perhaps a z-index issue, yet to debug) - FYI for folks who may have image covering the entire width of the screen and may be attributing the issue to the annotation not happening.
